add qwik example
grafbase/examples pull request #7
Opened 2022-12-12 17:50 UTC by hhthacker

qwik app using grafbase to add a plant with description and display existing plants

todo:
- typesafety on plantCollection index
- test readme instructions
- reload plant list upon adding another plant

2022-12-12 17:52 UTC, notrab commented on qwik/README.md
> +# Grafbase ⨯ Fresh
```suggestion
# Grafbase ⨯ Qwik
```

2022-12-12 17:53 UTC, notrab commented on qwik/README.md
> +This example uses the qwik web framework &mdash; [learn more](https://qwik.builder.io/docs/getting-started/)
```suggestion
This example uses the [Qwik](https://qwik.builder.io/docs/getting-started) web framework.
```

2022-12-12 17:54 UTC, notrab commented on qwik/package.json
> +  "name": "my-qwik-basic-starter",
```suggestion
```

2022-12-12 17:55 UTC, notrab commented on qwik/src/utils/grafbase.ts
> +    console.log('client', json.data)
```suggestion
```

2022-12-12 17:55 UTC, notrab commented on qwik/src/utils/grafbase.ts
> +          'x-api-key': import.meta.env.VITE_GRAFBASE_API_KEY as string
This is only used on the server, right?

2022-12-12 17:55 UTC, notrab commented on qwik/src/routes/index.tsx
> +  console.log('data', plantResource)
```suggestion
```

2022-12-12 17:57 UTC, notrab commented on qwik/src/routes/index.tsx
> +export const GetAllPlantsQuery = { query:
I would invoke this differently so the variables are "variables".

I'd instead do this:

```ts
const GetAllPlantsQuery = `
  query GetAllPlants($first: Int!) {
    plantCollection(first: $first) {
      edges {
        node {
          id
          name
          description
        }
      }
    }
  }
`
```

Then where invoked later on:

```ts
await grafbaseClient({query: GetAllPlantsQuery, variables: { first: 100 });
```

2022-12-12 17:58 UTC, notrab commented on qwik/src/routes/index.tsx
> +export const AddNewPlantMutation = (name: string, description: string) => ({ query:
I'd do the same as suggested above with the `GetAllPlantsQuery`.

```ts
await grafbaseClient(AddNewPlantMutation({ query: AddNewPlantMutation, variables: { name: newPlant.value, description: newPlantDescription.value })) 
```

2022-12-12 18:01 UTC, notrab requested changes
Looks awesome @hhthacker! Congrats on your first examples PR 🥳 

I've left a few comments that mostly address consistency with other examples.

We could change the schema so it uses the same as the Fresh example (Guestbook) so first-time users don't have to keep switching context but I might be overthinking that.

Let me know once it's ready for another review.

PS. I added over the weekend a root `README.md` which contain a link/description to a table. Feel free to add it there also.

2022-12-12 18:15 UTC, hhthacker commented on qwik/src/utils/grafbase.ts
> +          'x-api-key': import.meta.env.VITE_GRAFBASE_API_KEY as string
yes, would we remove it since the example is designed for locally running?

2022-12-12 18:19 UTC, hhthacker commented on qwik/README.md
> +## Please note
yes, thinking that different example project readmes are setup guides only, with extra resources and grafbase links in a central project readme

2022-12-13 11:26 UTC, notrab commented on qwik/src/utils/grafbase.ts
> +          'x-api-key': import.meta.env.VITE_GRAFBASE_API_KEY as string
Let's keep it. We should keep using the `.env` convention for examples so people can opt to deploy and use the hosted URLs if they wish.

2022-12-14 19:43 UTC, hhthacker commented
moved PR to monorepo, closing this one

2022-12-14 19:43 UTC, closed without merging